In [3]:
import numpy as np


In [5]:
a=[1,2,3]
arr= np.array(a)


In [6]:
type(a)


list

In [7]:
type(arr)

numpy.ndarray

In [8]:
print(arr)

[1 2 3]


In [9]:
arr.shape

(3,)

In [12]:
l1=[1,2,3,4]
l2=[5,6,7,8]

ar= np.array([l1,l2])

In [13]:
type(ar)

numpy.ndarray

In [14]:
ar.shape

(2, 4)

In [15]:
ar.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [17]:
ar.shape

(2, 4)

In [19]:
#indexing

arr

array([1, 2, 3])

In [20]:
arr[2]

3

In [21]:
arr

array([1, 2, 3])

In [22]:
arr[1]

2

In [23]:
ar[0:2,0:2]

array([[1, 2],
       [5, 6]])

In [25]:
ar

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [29]:
b= np.arange(0,10,step=2)

In [31]:
b

array([0, 2, 4, 6, 8])

In [4]:
np.linspace(1,10,30)

array([ 1.        ,  1.31034483,  1.62068966,  1.93103448,  2.24137931,
        2.55172414,  2.86206897,  3.17241379,  3.48275862,  3.79310345,
        4.10344828,  4.4137931 ,  4.72413793,  5.03448276,  5.34482759,
        5.65517241,  5.96551724,  6.27586207,  6.5862069 ,  6.89655172,
        7.20689655,  7.51724138,  7.82758621,  8.13793103,  8.44827586,
        8.75862069,  9.06896552,  9.37931034,  9.68965517, 10.        ])

In [5]:
b= np.arange(0,10)

In [6]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
b[3:]=100

In [8]:
b

array([  0,   1,   2, 100, 100, 100, 100, 100, 100, 100])

In [10]:
b1=b
b1[3:]=500
print(b1)

[  0   1   2 500 500 500 500 500 500 500]


In [11]:
b

array([  0,   1,   2, 500, 500, 500, 500, 500, 500, 500])

In [12]:
b1= b.copy()
print(b)
b1[3:]=1000
print(b1)

[  0   1   2 500 500 500 500 500 500 500]
[   0    1    2 1000 1000 1000 1000 1000 1000 1000]


In [13]:
b<500

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [14]:
b*2

array([   0,    2,    4, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [15]:
b[b<500]

array([0, 1, 2])

In [16]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [18]:
np.random.rand(3,3)*2

array([[0.60352376, 0.63331426, 0.93101369],
       [1.57547783, 1.94748327, 1.99850813],
       [0.20997893, 1.45637673, 0.74033136]])

In [20]:
np.random.randn(3,3)

array([[-0.88693382, -0.41585783,  0.18086686],
       [ 1.17222699, -0.50671627, -0.913587  ],
       [-1.35993645,  0.12622203, -0.30422724]])

In [21]:
np.random.randint(0,100,10).reshape(5,2)

array([[ 0, 36],
       [81, 12],
       [31, 35],
       [32, 47],
       [38,  7]])

In [24]:
np.random.random_sample((1,5))

array([[0.49577596, 0.75863232, 0.83818119, 0.9202848 , 0.99444971]])